import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRef } from 'react'

export default function Home() {
  const [goal, setGoal] = useState(100); //(Math.trunc(Math.random() * 100 + 50));
  const [count, setCount] = useState(0);
  const rCount = useRef(0);
  const [operand, setOperand] = useState(5); //(Math.trunc(Math.random() * 7 + 3));
  //let operand = Math.trunc(Math.random() * 7 + 3);

  function addition() {
    setCount(count + operand);
    rCount.current += operand;
    compareResult();
  }
  function subtraction() {
    setCount(count - operand);
    rCount.current -= operand;
    compareResult();
  }

  function multiplication() {
    setCount(count * operand);
    rCount.current *= operand;
    compareResult();
  }
  function division() {
    setCount(Math.trunc(count / operand));
    rCount.current = Math.trunc(rCount.current / operand);
    compareResult();
  }
  function compareResult() {
    if (goal != rCount.current) {
      setOperand(Math.trunc(Math.random() * 7 + 3));
    } else {
      alert('Congratulations!');
      setOperand(Math.trunc(Math.random() * 7 + 3));
      setGoal(Math.trunc(Math.random() * 100 + 50));
      //setCount(0);
      //rCount.current = 0;
    }
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Take me to {goal}
        </h1>

        <p className={styles.description}>
          Count: {count}
        </p>

        <div className={styles.grid} >
          <button className={styles.card} onClick={addition}>
            <h2>+{operand}</h2>
            <p>Add</p>
          </button>

          <button className={styles.card} onClick={subtraction}>
            <h2>-{operand}</h2>
            <p>Subtract</p>
          </button>

          <button className={styles.card} onClick={multiplication}>
            <h2>*{operand}</h2>
            <p>Multiply</p>
          </button>

          <button className={styles.card} onClick={division}>
            <h2>/{operand}</h2>
            <p>Divide</p>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by{' '}
          <span className={styles.logo}>
            <Image src="/Logo Hexa10 160x36.png" alt="Hexa10 Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
